//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCurrencyServicesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CryptoTbl
    {
        public int cryptoId { get; set; }
        public string fullName { get; set; }
        public string gander_ { get; set; }
        public int Crypto { get; set; }
        public string description { get; set; }
    }
}
