//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCurrencyServicesMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CryptoCurrencyDataEntities : DbContext
    {
        public CryptoCurrencyDataEntities()
            : base("name=CryptoCurrencyDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CryptoTbl> CryptoTbls { get; set; }
        public DbSet<AdminTbl> AdminTbls { get; set; }
        public DbSet<TblFeedback> TblFeedbacks { get; set; }
        public DbSet<TblRegister> TblRegisters { get; set; }
    }
}
